import { Calendar, Home, Inbox, Search, Settings } from "lucide-react";
import { MenuType } from "./menu-type";

export const HrPayrollMenu: MenuType[] = [
  {
    title: "Home",
    url: "/dashboard",
    icon: Home,
    isOpen: false,
    submenu: null,
  },
  {
    title: "Payroll Master",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Designation",
        url: "#",
        icon: Calendar,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Shift Info",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Create Roster Shift",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Set Holiday",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Department",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Eduction Entry",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Sections",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Nationality",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Education",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Line Mapping to Production",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Category",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Transport Stand",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Signing Option",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "OT Rule",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Salary Rule",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Weekend Setup",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Final Settlement Rule",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Late Deduction Setup",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Provident Fund Rule",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Install Provident Fund",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Staff Holiday Allowance",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Tiffin Bill Configure",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Leave Approval User",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Leave Approve HR User",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Salary Rule Setup",
        url: "#",
        icon: Search,
        isOpen: false,
        submenu: null,
      },
    ],
  },
  {
    title: "Employee Information",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Employee Info Entry",
        url: "#",
        icon: Home,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Employee Payroll",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
    ],
  },
  {
    title: "Attendance Correction",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Attendance Details",
        url: "#",
        icon: Home,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Micro Attendance",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },

      {
        title: "Micro",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Binary Attendance",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "OT Permision",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Shift Allocation",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Group Allocation",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
    ],
  },
  {
    title: "Payroll Report",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Daily Attendance",
        url: "#",
        icon: Home,
        isOpen: false,
        submenu: null,
      },
      {
        title: "New Recruitment",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },

      {
        title: "Employee Report",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Monthly Attendance",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Monthly Report",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Binary Report",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Report For Salary",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Salary Report",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Advantage Report",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
    ],
  },
  {
    title: "Salary Processing",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Advance-Dues-Deduction",
        url: "#",
        icon: Home,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Extra OT Entry",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },

      {
        title: "Extra OT Entry (Excel)",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Hour Punishment",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Leave Process",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Maternity Leave Entry",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Dinning Bill",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Salary Process",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Salary Setup",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
    ],
  },
  {
    title: "Advantage",
    url: "#",
    icon: Settings,
    isOpen: false,
    submenu: [
      {
        title: "Advance Salary Process",
        url: "#",
        icon: Home,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Festival Bonus Process",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },

      {
        title: "Lay-off Compensation",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Increment Entry",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Promotion Entry",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Earn Leave Process",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Final Settlement",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Manpower Requisition",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Employee Budget",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Staff OT Entry",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Allowance Process",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
      {
        title: "Insurance",
        url: "#",
        icon: Inbox,
        isOpen: false,
        submenu: null,
      },
    ],
  },
];
